services:
  - type: web
    name: btc-miner-prod
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: btc-miner-test
    env: python
    branch: rendertest
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: development
