services:
  - type: web
    name: orbital-bitcoin-mining-calculator
    env: python
    buildCommand: pip install -U pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
    healthCheckPath: "/health"